# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MCPERoleplay Beta Site
email: ...
description: > # this means to ignore newlines until "baseurl:"
 Welcome to the MCPERoleplay Beta Website, made by Jorti1. 
baseurl: "mcperoleplay.tk" # the subpath of your site, e.g. /blog
url: "http://mcperoleplay.tk" # the base hostname & protocol for your site
twitter_username: MCPERoleplay
github_username:  jorti1

# Build settings
markdown: kramdown

theme: jekyll-theme-slate
